baseURL = "https://polarhardboiled.github.io/hugotest"
languageCode = "fr"
theme = ["semantic"]
paginate = 5 # Number of items to show before paginating
title = "Zylla Hugo Test"
disqusShortname = "polarhardboiled"   # Change it to your Disqus shortname before using
DefaultContentLanguage = "fr"         # Theme i18n support
enableRobotsTXT = true # Suggested, enable robots.txt file
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params]
  SEOTitle = "Hugotest | Pour Zylla"
  description = "Comment tester le SSG Hugo"
  keyword = ""
  #author = "Zylla" # Optional, controls author name display on posts
  related_content_limit = 5
  since = 2008
  logo = "images/avatar.png"

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content
