baseURL = "https://polarhardboiled.github.io/hugotest"
title = "Hugo Test"
languageCode = "fr-fr"
paginate = 6
enableRobotsTXT =  true
buildDrafts =  false
buildFuture =  false
buildExpired =  false
theme = "papermod"

[Params]
  columns = 2
  themeOptions = ["base","roseate","auburn","beryl"] # select options for site color theme
  dateFormat = "2 January 2006"
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  viewportSize = "widest"
  enableUiAnimation = true
  enableBreadcrumb = false
  summaryShape = "classic"
  logoText = "Hugo Test"
  description = "Un Site pour tester Hugo et le theme switch"
  hideSingleContentsWhenJSDisabled = false
  minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud
  enableSkinChange = true
  
  siteBrandFontSize = 1
  fontUnit = "em"
  largestFontSize = 2.5
  smallestFontSize = 1

[Params.style]
    
    # To Enable Skins change
    presets = [ "base", "roseate", "auburn", "beryl" ]

[outputFormats]

  [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON",
  "SearchIndex"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
